// System-wide Constants, Enums, Roles, Permissions, Scopes, and Navigation Registry

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  HR_ADMIN: 'HR_ADMIN',
  HR_EXECUTIVE: 'HR_EXECUTIVE',
  RECRUITER: 'RECRUITER',
  PAYROLL_ADMIN: 'PAYROLL_ADMIN',
  TRAINING_ADMIN: 'TRAINING_ADMIN',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE'
};

export const DATA_SCOPES = {
  ALL: 'ALL',
  DEPARTMENT: 'DEPARTMENT',
  TEAM: 'TEAM',
  ASSIGNED: 'ASSIGNED',
  SELF: 'SELF',
  NONE: 'NONE'
};

export const PERMISSIONS = {
  // Navigation / Views
  DASHBOARD_VIEW: 'dashboard.view',
  RECRUITMENT_VIEW: 'recruitment.view',
  ONBOARDING_VIEW: 'onboarding.view',
  EMPLOYEE_VIEW: 'employee.view',
  EMPLOYEE_DIRECTORY_VIEW: 'employee.directory.view',
  EMPLOYEE_SENSITIVE_VIEW: 'employee.sensitive.view',
  EMPLOYEE_SELF_VIEW: 'employee.self.view',
  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_SELF_VIEW: 'attendance.self.view',
  PAYROLL_VIEW: 'payroll.view',
  PAYROLL_SELF_VIEW: 'payroll.self.view',
  PAYSLIP_SELF_DOWNLOAD: 'payslip.self.download',
  TRAINING_VIEW: 'training.view',
  TRAINING_SELF_VIEW: 'training.self.view',
  PERFORMANCE_VIEW: 'performance.view',
  PERFORMANCE_SELF_VIEW: 'performance.self.view',
  EXIT_VIEW: 'exit.view',
  EXIT_SELF_CREATE: 'exit.self.create',
  REPORTS_VIEW: 'reports.view',
  SETTINGS_VIEW: 'settings.view',
  HEALTH_VIEW: 'health.view',
  AUDIT_VIEW: 'audit.view',

  // Management / Actions
  RECRUITMENT_CREATE: 'recruitment.create',
  RECRUITMENT_EDIT: 'recruitment.edit',
  RECRUITMENT_SCREEN: 'recruitment.screen',
  RECRUITMENT_SHORTLIST: 'recruitment.shortlist',
  RECRUITMENT_REJECT: 'recruitment.reject',
  RECRUITMENT_INTERVIEW_MOVE: 'recruitment.interview.move',
  RECRUITMENT_SELECT: 'recruitment.select',

  ONBOARDING_MANAGE: 'onboarding.manage',

  EMPLOYEE_CREATE: 'employee.create',
  EMPLOYEE_EDIT: 'employee.edit',
  EMPLOYEE_DELETE: 'employee.delete',

  ATTENDANCE_MANAGE: 'attendance.manage',
  LEAVE_APPLY: 'leave.apply',
  LEAVE_APPROVE: 'leave.approve',

  PAYROLL_PROCESS: 'payroll.process',

  TRAINING_MANAGE: 'training.manage',

  PERFORMANCE_GOAL_CREATE_SELF: 'performance.goal.create.self',
  PERFORMANCE_GOAL_MANAGE_TEAM: 'performance.goal.manage.team',
  PERFORMANCE_REVIEW: 'performance.review',

  EXIT_PROCESS: 'exit.process',

  SETTINGS_MANAGE: 'settings.manage',
  USER_MANAGE: 'user.manage'
};

// Centralized Page Authorization Map supporting anyOf (or) permission rules
export const PAGE_PERMISSION_MAP = {
  'Dashboard': [PERMISSIONS.DASHBOARD_VIEW],
  'Recruitment': [PERMISSIONS.RECRUITMENT_VIEW],
  'Onboarding': [PERMISSIONS.ONBOARDING_VIEW],
  'Employees': [PERMISSIONS.EMPLOYEE_VIEW, PERMISSIONS.EMPLOYEE_DIRECTORY_VIEW, PERMISSIONS.EMPLOYEE_SELF_VIEW],
  'Attendance & Leave': [PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_SELF_VIEW, PERMISSIONS.LEAVE_APPLY],
  'Payroll': [PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_SELF_VIEW],
  'Training': [PERMISSIONS.TRAINING_VIEW, PERMISSIONS.TRAINING_SELF_VIEW],
  'Performance': [PERMISSIONS.PERFORMANCE_VIEW, PERMISSIONS.PERFORMANCE_SELF_VIEW],
  'Exit Management': [PERMISSIONS.EXIT_VIEW, PERMISSIONS.EXIT_SELF_CREATE],
  'Reports': [PERMISSIONS.REPORTS_VIEW],
  'Settings': [PERMISSIONS.SETTINGS_VIEW],
  'System Health': [PERMISSIONS.HEALTH_VIEW]
};

// Role-specific navigation labels mapping
export const ROLE_NAV_LABELS = {
  [ROLES.RECRUITER]: {
    'Recruitment': 'Assigned Jobs & Pipelines',
    'Employees': 'My Profile',
    'Attendance & Leave': 'My Attendance',
    'Payroll': 'My Payslips',
    'Training': 'My Learning',
    'Performance': 'My Goals',
    'Exit Management': 'My Exit'
  },
  [ROLES.PAYROLL_ADMIN]: {
    'Employees': 'Employee Directory',
    'Attendance & Leave': 'Attendance Inputs',
    'Payroll': 'Payroll Runs & Payslips',
    'Training': 'My Learning',
    'Performance': 'My Goals',
    'Exit Management': 'My Exit'
  },
  [ROLES.TRAINING_ADMIN]: {
    'Employees': 'Employee Directory',
    'Attendance & Leave': 'My Attendance',
    'Payroll': 'My Payslips',
    'Training': 'Programs & Assignments',
    'Performance': 'My Goals',
    'Exit Management': 'My Exit'
  },
  [ROLES.MANAGER]: {
    'Recruitment': 'Assigned Interviews',
    'Employees': 'My Team',
    'Attendance & Leave': 'Team Attendance & Leave',
    'Payroll': 'My Payslips',
    'Training': 'Team Learning',
    'Performance': 'Team Goals & Reviews',
    'Exit Management': 'Team Exit'
  },
  [ROLES.EMPLOYEE]: {
    'Employees': 'My Profile',
    'Attendance & Leave': 'My Attendance & Leave',
    'Payroll': 'My Payslips',
    'Training': 'My Learning',
    'Performance': 'My Goals & Reviews',
    'Exit Management': 'Resignation & Exit'
  }
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.HR_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.RECRUITMENT_VIEW, PERMISSIONS.RECRUITMENT_CREATE, PERMISSIONS.RECRUITMENT_EDIT, PERMISSIONS.RECRUITMENT_SCREEN, PERMISSIONS.RECRUITMENT_SHORTLIST, PERMISSIONS.RECRUITMENT_REJECT, PERMISSIONS.RECRUITMENT_INTERVIEW_MOVE, PERMISSIONS.RECRUITMENT_SELECT,
    PERMISSIONS.ONBOARDING_VIEW, PERMISSIONS.ONBOARDING_MANAGE,
    PERMISSIONS.EMPLOYEE_VIEW, PERMISSIONS.EMPLOYEE_DIRECTORY_VIEW, PERMISSIONS.EMPLOYEE_SENSITIVE_VIEW, PERMISSIONS.EMPLOYEE_SELF_VIEW, PERMISSIONS.EMPLOYEE_CREATE, PERMISSIONS.EMPLOYEE_EDIT, PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_SELF_VIEW, PERMISSIONS.ATTENDANCE_MANAGE, PERMISSIONS.LEAVE_APPLY, PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_SELF_VIEW, PERMISSIONS.PAYSLIP_SELF_DOWNLOAD, PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.TRAINING_VIEW, PERMISSIONS.TRAINING_SELF_VIEW, PERMISSIONS.TRAINING_MANAGE,
    PERMISSIONS.PERFORMANCE_VIEW, PERMISSIONS.PERFORMANCE_SELF_VIEW, PERMISSIONS.PERFORMANCE_GOAL_CREATE_SELF, PERMISSIONS.PERFORMANCE_GOAL_MANAGE_TEAM, PERMISSIONS.PERFORMANCE_REVIEW,
    PERMISSIONS.EXIT_VIEW, PERMISSIONS.EXIT_SELF_CREATE, PERMISSIONS.EXIT_PROCESS,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.HEALTH_VIEW
  ],
  [ROLES.HR_EXECUTIVE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.RECRUITMENT_VIEW, PERMISSIONS.RECRUITMENT_CREATE, PERMISSIONS.RECRUITMENT_EDIT, PERMISSIONS.RECRUITMENT_SCREEN, PERMISSIONS.RECRUITMENT_SHORTLIST, PERMISSIONS.RECRUITMENT_REJECT, PERMISSIONS.RECRUITMENT_INTERVIEW_MOVE, PERMISSIONS.RECRUITMENT_SELECT,
    PERMISSIONS.ONBOARDING_VIEW, PERMISSIONS.ONBOARDING_MANAGE,
    PERMISSIONS.EMPLOYEE_VIEW, PERMISSIONS.EMPLOYEE_DIRECTORY_VIEW, PERMISSIONS.EMPLOYEE_SENSITIVE_VIEW, PERMISSIONS.EMPLOYEE_SELF_VIEW, PERMISSIONS.EMPLOYEE_CREATE, PERMISSIONS.EMPLOYEE_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_SELF_VIEW, PERMISSIONS.ATTENDANCE_MANAGE, PERMISSIONS.LEAVE_APPLY, PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.PAYROLL_SELF_VIEW, PERMISSIONS.PAYSLIP_SELF_DOWNLOAD,
    PERMISSIONS.TRAINING_VIEW, PERMISSIONS.TRAINING_SELF_VIEW, PERMISSIONS.TRAINING_MANAGE,
    PERMISSIONS.PERFORMANCE_VIEW, PERMISSIONS.PERFORMANCE_SELF_VIEW, PERMISSIONS.PERFORMANCE_GOAL_CREATE_SELF, PERMISSIONS.PERFORMANCE_GOAL_MANAGE_TEAM, PERMISSIONS.PERFORMANCE_REVIEW,
    PERMISSIONS.EXIT_VIEW, PERMISSIONS.EXIT_SELF_CREATE, PERMISSIONS.EXIT_PROCESS,
    PERMISSIONS.REPORTS_VIEW
  ],
  [ROLES.RECRUITER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.RECRUITMENT_VIEW, PERMISSIONS.RECRUITMENT_CREATE, PERMISSIONS.RECRUITMENT_EDIT, PERMISSIONS.RECRUITMENT_SCREEN, PERMISSIONS.RECRUITMENT_SHORTLIST, PERMISSIONS.RECRUITMENT_REJECT, PERMISSIONS.RECRUITMENT_INTERVIEW_MOVE,
    PERMISSIONS.EMPLOYEE_DIRECTORY_VIEW, PERMISSIONS.EMPLOYEE_SELF_VIEW,
    PERMISSIONS.ATTENDANCE_SELF_VIEW, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.PAYROLL_SELF_VIEW, PERMISSIONS.PAYSLIP_SELF_DOWNLOAD,
    PERMISSIONS.TRAINING_SELF_VIEW,
    PERMISSIONS.PERFORMANCE_SELF_VIEW, PERMISSIONS.PERFORMANCE_GOAL_CREATE_SELF,
    PERMISSIONS.EXIT_SELF_CREATE
  ],
  [ROLES.PAYROLL_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EMPLOYEE_VIEW, PERMISSIONS.EMPLOYEE_DIRECTORY_VIEW, PERMISSIONS.EMPLOYEE_SENSITIVE_VIEW, PERMISSIONS.EMPLOYEE_SELF_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_SELF_VIEW, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_SELF_VIEW, PERMISSIONS.PAYSLIP_SELF_DOWNLOAD, PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.TRAINING_SELF_VIEW,
    PERMISSIONS.PERFORMANCE_SELF_VIEW, PERMISSIONS.PERFORMANCE_GOAL_CREATE_SELF,
    PERMISSIONS.EXIT_SELF_CREATE
  ],
  [ROLES.TRAINING_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EMPLOYEE_DIRECTORY_VIEW, PERMISSIONS.EMPLOYEE_SELF_VIEW,
    PERMISSIONS.ATTENDANCE_SELF_VIEW, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.PAYROLL_SELF_VIEW, PERMISSIONS.PAYSLIP_SELF_DOWNLOAD,
    PERMISSIONS.TRAINING_VIEW, PERMISSIONS.TRAINING_SELF_VIEW, PERMISSIONS.TRAINING_MANAGE,
    PERMISSIONS.PERFORMANCE_SELF_VIEW, PERMISSIONS.PERFORMANCE_GOAL_CREATE_SELF,
    PERMISSIONS.EXIT_SELF_CREATE
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.RECRUITMENT_VIEW, PERMISSIONS.RECRUITMENT_INTERVIEW_MOVE,
    PERMISSIONS.EMPLOYEE_DIRECTORY_VIEW, PERMISSIONS.EMPLOYEE_SELF_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_SELF_VIEW, PERMISSIONS.LEAVE_APPLY, PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.PAYROLL_SELF_VIEW, PERMISSIONS.PAYSLIP_SELF_DOWNLOAD,
    PERMISSIONS.TRAINING_SELF_VIEW,
    PERMISSIONS.PERFORMANCE_VIEW, PERMISSIONS.PERFORMANCE_SELF_VIEW, PERMISSIONS.PERFORMANCE_GOAL_CREATE_SELF, PERMISSIONS.PERFORMANCE_GOAL_MANAGE_TEAM, PERMISSIONS.PERFORMANCE_REVIEW,
    PERMISSIONS.EXIT_VIEW, PERMISSIONS.EXIT_SELF_CREATE
  ],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.EMPLOYEE_SELF_VIEW,
    PERMISSIONS.ATTENDANCE_SELF_VIEW, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.PAYROLL_SELF_VIEW, PERMISSIONS.PAYSLIP_SELF_DOWNLOAD,
    PERMISSIONS.TRAINING_SELF_VIEW,
    PERMISSIONS.PERFORMANCE_SELF_VIEW, PERMISSIONS.PERFORMANCE_GOAL_CREATE_SELF,
    PERMISSIONS.EXIT_SELF_CREATE
  ]
};

export const ROLE_DATA_SCOPES = {
  [ROLES.SUPER_ADMIN]: { Jobs: 'ALL', Candidates: 'ALL', Employees: 'ALL', Attendance: 'ALL', LeaveRequests: 'ALL', LeaveBalances: 'ALL', Payroll: 'ALL', PayrollItems: 'ALL', TrainingPrograms: 'ALL', TrainingAssignments: 'ALL', PerformanceGoals: 'ALL', PerformanceReviews: 'ALL', ExitRequests: 'ALL' },
  [ROLES.HR_ADMIN]: { Jobs: 'ALL', Candidates: 'ALL', Employees: 'ALL', Attendance: 'ALL', LeaveRequests: 'ALL', LeaveBalances: 'ALL', Payroll: 'ALL', PayrollItems: 'ALL', TrainingPrograms: 'ALL', TrainingAssignments: 'ALL', PerformanceGoals: 'ALL', PerformanceReviews: 'ALL', ExitRequests: 'ALL' },
  [ROLES.HR_EXECUTIVE]: { Jobs: 'ALL', Candidates: 'ALL', Employees: 'ALL', Attendance: 'ALL', LeaveRequests: 'ALL', LeaveBalances: 'ALL', Payroll: 'SELF', PayrollItems: 'SELF', TrainingPrograms: 'ALL', TrainingAssignments: 'ALL', PerformanceGoals: 'ALL', PerformanceReviews: 'ALL', ExitRequests: 'ALL' },
  [ROLES.RECRUITER]: { Jobs: 'ASSIGNED', Candidates: 'ASSIGNED', Employees: 'ALL', Attendance: 'SELF', LeaveRequests: 'SELF', LeaveBalances: 'SELF', Payroll: 'NONE', PayrollItems: 'SELF', TrainingPrograms: 'SELF', TrainingAssignments: 'SELF', PerformanceGoals: 'SELF', PerformanceReviews: 'SELF', ExitRequests: 'SELF' },
  [ROLES.PAYROLL_ADMIN]: { Jobs: 'NONE', Candidates: 'NONE', Employees: 'ALL', Attendance: 'ALL', LeaveRequests: 'ALL', LeaveBalances: 'ALL', Payroll: 'ALL', PayrollItems: 'ALL', TrainingPrograms: 'NONE', TrainingAssignments: 'SELF', PerformanceGoals: 'SELF', PerformanceReviews: 'NONE', ExitRequests: 'SELF' },
  [ROLES.TRAINING_ADMIN]: { Jobs: 'NONE', Candidates: 'NONE', Employees: 'ALL', Attendance: 'SELF', LeaveRequests: 'SELF', LeaveBalances: 'SELF', Payroll: 'NONE', PayrollItems: 'SELF', TrainingPrograms: 'ALL', TrainingAssignments: 'ALL', PerformanceGoals: 'SELF', PerformanceReviews: 'NONE', ExitRequests: 'SELF' },
  [ROLES.MANAGER]: { Jobs: 'ASSIGNED', Candidates: 'ASSIGNED', Employees: 'TEAM', Attendance: 'TEAM', LeaveRequests: 'TEAM', LeaveBalances: 'TEAM', Payroll: 'NONE', PayrollItems: 'SELF', TrainingPrograms: 'TEAM', TrainingAssignments: 'TEAM', PerformanceGoals: 'TEAM', PerformanceReviews: 'TEAM', ExitRequests: 'TEAM' },
  [ROLES.EMPLOYEE]: { Jobs: 'NONE', Candidates: 'NONE', Employees: 'SELF', Attendance: 'SELF', LeaveRequests: 'SELF', LeaveBalances: 'SELF', Payroll: 'NONE', PayrollItems: 'SELF', TrainingPrograms: 'SELF', TrainingAssignments: 'SELF', PerformanceGoals: 'SELF', PerformanceReviews: 'SELF', ExitRequests: 'SELF' }
};

/**
 * Human-readable Enum Formatter Utility
 */
export function formatEnumLabel(val) {
  if (!val) return 'N/A';
  const text = String(val).replace(/_/g, ' ').toLowerCase();
  return text.charAt(0).toUpperCase() + text.slice(1);
}

export const JOB_STATUSES = {
  DRAFT: 'DRAFT',
  OPEN: 'OPEN',
  ON_HOLD: 'ON_HOLD',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED'
};

export const PIPELINE_STAGES = {
  NEW: 'NEW',
  AI_SCREENING: 'AI_SCREENING',
  AI_REVIEWED: 'AI_REVIEWED',
  SHORTLISTED: 'SHORTLISTED',
  INTERVIEW_1: 'INTERVIEW_1',
  INTERVIEW_2: 'INTERVIEW_2',
  FINAL_INTERVIEW: 'FINAL_INTERVIEW',
  SELECTED: 'SELECTED',
  OFFER_SENT: 'OFFER_SENT',
  OFFER_ACCEPTED: 'OFFER_ACCEPTED',
  JOINED: 'JOINED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN'
};

export const AI_RECOMMENDATIONS = {
  STRONG_SHORTLIST: 'STRONG_SHORTLIST',
  SHORTLIST: 'SHORTLIST',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  LOW_MATCH: 'LOW_MATCH'
};

export const CANDIDATE_AI_STATUSES = {
  RECEIVED: 'RECEIVED',
  QUEUED: 'QUEUED',
  EXTRACTING: 'EXTRACTING',
  EXTRACTED: 'EXTRACTED',
  AI_PROCESSING: 'AI_PROCESSING',
  AI_COMPLETED: 'AI_COMPLETED',
  FAILED: 'FAILED',
  MANUAL_REVIEW: 'MANUAL_REVIEW'
};

export const ONBOARDING_TASK_STATUSES = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  WAIVED: 'WAIVED'
};

export const ATTENDANCE_STATUSES = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  HALF_DAY: 'HALF_DAY',
  LATE: 'LATE',
  LEAVE: 'LEAVE',
  HOLIDAY: 'HOLIDAY',
  WEEK_OFF: 'WEEK_OFF',
  WORK_FROM_HOME: 'WORK_FROM_HOME'
};

export const LEAVE_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

export const PAYROLL_STATUSES = {
  DRAFT: 'DRAFT',
  REVIEW: 'REVIEW',
  APPROVED: 'APPROVED',
  PROCESSED: 'PROCESSED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED'
};

export const ID_PREFIXES = {
  JOB: 'JOB-',
  CANDIDATE: 'CAN-',
  SCREENING: 'SCR-',
  EMPLOYEE: 'EMP-',
  DEPARTMENT: 'DEP-',
  DESIGNATION: 'DSG-',
  ATTENDANCE: 'ATT-',
  LEAVE: 'LEV-',
  TRAINING: 'TRN-',
  GOAL: 'GOL-',
  REVIEW: 'REV-',
  EXIT: 'EXT-'
};
